global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node_exporter'

    static_configs:

      - targets: ['10.0.1.97:9100']
      - targets: ['10.0.2.219:9100']


    